### ISSUE TITLE
Please upgrade aurora-postgresql-pgvector to 0.5.1 as it supports HNSW indexes

### ISSUE THREAD

**Issue by sushgandhi** [aws-samples/aurora-postgresql-pgvector#4]
Please upgrade aurora-postgresql-pgvector to 0.5.1 as it supports HNSW indexes
Currently the latest version is 0.4.4

**Comment by shayons** [comment]
Thanks for your feedback. We will be refreshing the modules very soon. Stay tuned!

**Comment by shayons** [comment]
Thanks for your feedback. We will be refreshing the modules very soon. Stay tuned!
